db:
  host: localhost
  port: 27017
  player_sqlite_file: db.sqlite
  db_sqlite_file: main.sqlite

player:
  # Number of times to poll player api per second. If set too high (around 10) rate limits will start to apply
  req_per_second: 4
  # After how many requests to log a summary. Too low and logs will grow quickly.
  log_after: 10
  # How often to insert states into database.
  batch_size_insert: 100

gen_events:
  enable: false
  # If less than this percent (0-1) at end of song then generate skip
  skip_thresh: 0.95
  # Length of jump in playback of a song to generate a seek event
  seek_limit: 1500
  # When to generate new events from inactive states (not really used anymore)
  inactive_time_thresh_ms: 1000

gdpr:
  # Location of spotify GDPR export
  export_path: download/StreamingHistory.json

sounds_good:
  # The Sounds Good playlist id
  playlist_id: 0P6cerId9ZFhdr4kHEmTry
  # Archive playlist to move to afer move_afer_days days
  move_to_playlist: 3ZEphevFVeYJin3VKfapgl
  # Spotify user associated with API credentials
  user_id: benbanerjeerichards
  # Move from playlist_id to move_to_playlist if not saved to library within move_after_days
  move_after_days: 30

archive_player:
  percent_to_archive: 0.95

export:
  enable: false